# vim:sw=2:et:

os: linux
dist: xenial
language: elixir
notifications:
  email:
    recipients:
      - alerts@rabbitmq.com
    on_success: never
    on_failure: always
addons:
  apt:
    packages:
      - awscli
cache:
  apt: true
env:
  global:
    - secure: mBGK2Yw6xJtIRD0V3JU9iwA8fkbkwcRO9i5ocKMi6g2/ub3cWylvJJCX1ZnLR4EEB3xtP60+XCl40g6V+qM4GEDqoT4nE8neEyajbhmKIFVuYnU29sC0czFuj9TpQ2gJyW//KhNX+sz8IpL78iQiMy+d1mK7sNWE8l1lCbcFeddu+Zr5BQ2YXJYP+NGLjkkpL59gYiXP9y5pfHbkoAAN+tS1/boCf8l29y6p83KMgvT/PL7vJXSwDgo48mfymipZOBEgsCFmoC6/QkrpsCrLAMiRGQB2l8uT2YOwF5BsioxSOggYkr3yJ7cOtoYPzB+AJQwxuiOYtDyga6qxFJKghW4wunXuGXHT+/sYKsJl/rMdbFpszAPNCIeXXfrxOAPNTq9IhyIKrqQRHKXGS95fySWTZ2AahpUKDcrw1zmWiS5Y35y87nNYYDQYQUFcuLMbADI5H+WAyZOidIoJwNY35R5CKMPG1zayxalgwBlbAbq/uLOhznoJ9KgoFzNwG7Ms7ND1Bpvb11L342N84vBqt7uvW9LPZ+2Mm82PeypBCAQOzPchk4XPjJxEHaSbcnZvexFOirOD9Xe9gyQFTVl2U7dnNG95Rlm2UP/r0MfuvIstw/WZ3d1sQNRlgesUaWGbWARmH1GmRelxLLz71MUqEz6VIHphjjycPwooc3q1pyU=
    - secure: RJ5MM2YJB3tidhtbJAQ0EPOfiGzCBMcxwm7aVYPig5bQHzgLLM323GgMYG0i/UTDqdxAilUSMSCq115Bq9e0xdrWzn3ogn+Tg9BCZ1aWB8nq+HOoGKTGsFW2ZAyNNsgMoZG2444TBF5oAFKx+GpeN10lE/mThxuDckwePjWK/8jcwWiw1G6u9dwYqKkRiW0wVqGhQtB9V7UQXVY1ENp/EPxarssjcJt5DH+30WtVsQNrHi3qIBG8D9EHfVcZSK2gaaurz3ef7iaXg6UqMQZSnz2p+r7xahy2bYGiEcbWZZIGMyIRzdH6eTe3tpkkN3rZBBKnR+UM3Vd0p59D+CSWnicO01JLinDQgkfYAxy1DlC2IGzVmtMlOmz1wxZZwVajII9ySG/YvE2SXX1T3nBDNpcPAldGVc2qTyQdJMEA3Hrr/aMqePp352y0aLk44i3xJTKoNMZh3xitZLWGBS1XcNA3fk41THFzcOPuK39Kx86yTltigZvKiQ6HBUS1W5O3rE98IR95S65xDpxRcHm9Rerv4SBkUZkrEuNIW1aTSyX5pV6qdw4vXcfprI0gz2FVXCWmapL4yWbKn9STNH4bLD3JhJpWjzp3eqp78M0rvY5gtLRnwO6JIbxAc1oNTB/UrR2xIcDJgwoslVqJaK4bWOCzmNztkPsZ/7VCyPIiGQg=

    # $base_rmq_ref is used by rabbitmq-components.mk to select the
    # appropriate branch for dependencies.
    - base_rmq_ref=master

elixir:
  - '1.9'
otp_release:
  - '21.3'
  - '22.2'

install:
  # This project being an Erlang one (we just set language to Elixir
  # to ensure it is installed), we don't want Travis to run mix(1)
  # automatically as it will break.
  skip

script:
  # $current_rmq_ref is also used by rabbitmq-components.mk to select
  # the appropriate branch for dependencies.
  - make check-rabbitmq-components.mk
    current_rmq_ref="${TRAVIS_PULL_REQUEST_BRANCH:-${TRAVIS_BRANCH}}"
  - make xref
    current_rmq_ref="${TRAVIS_PULL_REQUEST_BRANCH:-${TRAVIS_BRANCH}}"
  - make tests
    current_rmq_ref="${TRAVIS_PULL_REQUEST_BRANCH:-${TRAVIS_BRANCH}}"

after_failure:
  - |
    cd "$TRAVIS_BUILD_DIR"
    if test -d logs && test "$AWS_ACCESS_KEY_ID" && test "$AWS_SECRET_ACCESS_KEY"; then
      archive_name="$(basename "$TRAVIS_REPO_SLUG")-$TRAVIS_JOB_NUMBER"

      tar -c --transform "s/^logs/${archive_name}/" -f - logs | \
        xz > "${archive_name}.tar.xz"

      aws s3 cp "${archive_name}.tar.xz" s3://server-release-pipeline/travis-ci-logs/ \
        --region eu-west-1 \
        --acl public-read
    fi
