#!/bin/sh
##  The contents of this file are subject to the Mozilla Public License
##  Version 1.1 (the "License"); you may not use this file except in
##  compliance with the License. You may obtain a copy of the License
##  at http://www.mozilla.org/MPL/
##
##  Software distributed under the License is distributed on an "AS IS"
##  basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
##  the License for the specific language governing rights and
##  limitations under the License.
##
##  The Original Code is RabbitMQ.
##
##  The Initial Developer of the Original Code is VMware, Inc.
##  Copyright (c) 2012 VMware, Inc.  All rights reserved.
##

### generic-unix ###
### next line potentially updated in package install steps
SYS_PREFIX=${RABBITMQ_HOME}

check_and_set_rabbitmq_file_location() {
    # $1 - var name (set), $2 - global location, $3 - optional suffix for check
    [ -f $2$3 ] && [ ! -f ${SYS_PREFIX}$2$3 ] && \
        echo "WARNING: $1 default is \"${SYS_PREFIX}$2\" although \"$2$3\" exists."
    eval "$1=${SYS_PREFIX}$2"
}

## Set default values

check_and_set_rabbitmq_file_location CONF_ENV_FILE        /etc/rabbitmq/rabbitmq-env.conf
check_and_set_rabbitmq_file_location CONFIG_FILE          /etc/rabbitmq/rabbitmq           .config
check_and_set_rabbitmq_file_location ENABLED_PLUGINS_FILE /etc/rabbitmq/enabled-plugins
check_and_set_rabbitmq_file_location LOG_BASE             /var/log/rabbitmq
check_and_set_rabbitmq_file_location MNESIA_BASE          /var/lib/rabbitmq/mnesia

PLUGINS_DIR="${RABBITMQ_HOME}/plugins"

