pull_request_rules:
  - name: Add bazel label if a Bazel file is modified
    conditions:
      - files~=\.(bazel|bzl)$
    actions:
      label:
        add:
          - bazel
  - name: Add make label if a Make file is modified
    conditions:
      - files~=(Makefile|\.mk)$
    actions:
      label:
        add:
          - make
  - name: Automatically backport to v3.10.x based on label
    conditions:
      - base=master
      - label=backport-v3.10.x
      - label!=backport-v3.9.x
      - label!=backport-v3.8.x
    actions:
      backport:
        branches:
          - v3.10.x
        assignees:
          - "{{ author }}"
  - name: Automatically backport to v3.10.x & v3.9.x based on labels
    conditions:
      - base=master
      - label=backport-v3.10.x
      - label=backport-v3.9.x
      - label!=backport-v3.8.x
    actions:
      backport:
        branches:
          - v3.10.x
        labels:
          - backport-v3.9.x
        assignees:
          - "{{ author }}"
  - name: Automatically backport to v3.10.x, v3.9.x & v3.8.x based on labels
    conditions:
      - base=master
      - label=backport-v3.10.x
      - label=backport-v3.9.x
      - label=backport-v3.8.x
    actions:
      backport:
        branches:
          - v3.10.x
        labels:
          - backport-v3.9.x
          - backport-v3.8.x
        assignees:
          - "{{ author }}"
  - name: Automatically backport to v3.9.x based on label
    conditions:
      - base=v3.10.x
      - label=backport-v3.9.x
      - label!=backport-v3.8.x
    actions:
      backport:
        branches:
          - v3.9.x
        assignees:
          - "{{ author }}"
  - name: Automatically backport to v3.9.x & v3.8.x based on labels
    conditions:
      - base=v3.10.x
      - label=backport-v3.9.x
      - label=backport-v3.8.x
    actions:
      backport:
        branches:
          - v3.9.x
        labels:
          - backport-v3.8.x
        assignees:
          - "{{ author }}"
  - name: Automatically backport to v3.8.x based on label
    conditions:
      - base=v3.9.x
      - label=backport-v3.8.x
    actions:
      backport:
        branches:
          - v3.8.x
        assignees:
          - "{{ author }}"
