pull_request_rules:
  - name: Add make label if a Make file is modified
    conditions:
      - files~=(Makefile|\.mk)$
    actions:
      label:
        add:
          - make
  - name: Automatically backport to v4.2.x (with cascade to v4.1.x)
    conditions:
      - base=main
      - label=backport-v4.2.x
      - label=backport-v4.1.x
    actions:
      backport:
        branches:
          - v4.2.x
        assignees:
          - "{{ author }}"
        labels:
          - backport-v4.1.x
  - name: Automatically backport to v4.2.x (without cascade)
    conditions:
      - base=main
      - label=backport-v4.2.x
      - label!=backport-v4.1.x
    actions:
      backport:
        branches:
          - v4.2.x
        assignees:
          - "{{ author }}"
  - name: Automatically backport to v4.1.x based on label
    conditions:
      - base=v4.2.x
      - label=backport-v4.1.x
    actions:
      backport:
        branches:
          - v4.1.x
        assignees:
          - "{{ author }}"
