#!/usr/bin/env escript
%% -*- erlang -*-

main(SrcDirs) ->
    Modules = [list_to_atom(filename:basename(F, ".erl")) ||
                  SrcDir <- SrcDirs,
                  F <- filelib:wildcard("*.erl", SrcDir)],
    {ok, {application, Application, Properties}} = io:read(''),
    NewProperties =
        case proplists:get_value(modules, Properties) of
            [] -> lists:keyreplace(modules, 1, Properties, {modules, Modules});
            _  -> Properties
        end,
    io:format("~p.~n", [{application, Application, NewProperties}]).
