#!/bin/sh
##   The contents of this file are subject to the Mozilla Public License
##   Version 1.1 (the "License"); you may not use this file except in
##   compliance with the License. You may obtain a copy of the License at
##   http://www.mozilla.org/MPL/
##
##   Software distributed under the License is distributed on an "AS IS"
##   basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
##   License for the specific language governing rights and limitations
##   under the License.
##
##   The Original Code is RabbitMQ.
##
##   The Initial Developers of the Original Code are LShift Ltd,
##   Cohesive Financial Technologies LLC, and Rabbit Technologies Ltd.
##
##   Portions created before 22-Nov-2008 00:00:00 GMT by LShift Ltd,
##   Cohesive Financial Technologies LLC, or Rabbit Technologies Ltd
##   are Copyright (C) 2007-2008 LShift Ltd, Cohesive Financial
##   Technologies LLC, and Rabbit Technologies Ltd.
##
##   Portions created by LShift Ltd are Copyright (C) 2007-2009 LShift
##   Ltd. Portions created by Cohesive Financial Technologies LLC are
##   Copyright (C) 2007-2009 Cohesive Financial Technologies
##   LLC. Portions created by Rabbit Technologies Ltd are Copyright
##   (C) 2007-2009 Rabbit Technologies Ltd.
##
##   All Rights Reserved.
##
##   Contributor(s): ______________________________________.
##

# 
# Gentoo specific wrapper script for rabbitmq-multi to allow creation of logs with correct ownership

# rabbitmq-1.5.0-r1 installs to this location
DAEMON=/usr/sbin/rabbitmq-multi
    
    # we need this script installed correctly for us to work
    if [ ! -x "${DAEMON}" ] ;
    then
        echo "Error can't locate `basename $DAEMON` under `dirname $DAEMON`"
        exit `false`
    fi
    
    # output directed to stdout gets logged to this file
    info_log=$1
    shift 1
    if [ -z "${info_log}" ] ;
    then
        echo "Usage `basename $0` [--background] output-log error-log"
        exit `false`
    fi

    # output directed to stderr gets logged to this file
    error_log=$1
    shift 1
    if [ -z "${error_log}" ] ;
    then
        echo "Usage `basename $0` [--background] output-log error-log"
        exit `false`
    fi
      
    # duplicate stdin/stderr to logs and screen
    (   (   (                                \
                ${DAEMON} $*                 \
                3>&1 1>&2 2>&1               \
            ) | tee  ${info_log}             \
        ) 3>&2 2>&1 1>&3 | tee  ${error_log} \
    )
