{
 "title": "RabbitMQ Overview",
 "description": "RabbitMQ Management Overview page - https://www.rabbitmq.com/management.html",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Nodes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "File descriptors",
   "type": "graph",
   "description": "File descriptor count and limit, as reported by the operating system. The count includes network sockets and file handles.\n\nTo optimize disk access RabbitMQ uses as many free descriptors as are available, so the count may safely approach the limit. However, if most of the file descriptors are used by sockets then persister performance will be negatively impacted.\n\n* [Open File Handles Limit](https://www.rabbitmq.com/production-checklist.html#resource-limits-file-handle-limit)",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_node_fd_used", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Socket descriptors",
   "type": "graph",
   "description": "The network sockets count and limit managed by RabbitMQ.\n\nWhen the limit is exhausted RabbitMQ will stop accepting new network connections.\n\n* [Networking and RabbitMQ](https://www.rabbitmq.com/networking.html)\n* [Open File Handles Limit](https://www.rabbitmq.com/production-checklist.html#resource-limits-file-handle-limit)",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_node_sockets_used", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Erlang processes",
   "type": "graph",
   "description": "All work happens in an Erlang process - it's the basic unit of concurrency. Think of an Erlang process as a lightweight thread. A RabbitMQ queue is an Erlang process. Same for a channel, connection, vhost or message store.",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rabbitmq_node_proc_used", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "Memory Resident Set Size used by the Erlang VM, as measured by the OS kernel.\n\n* [Reasoning About Memory Use](https://www.rabbitmq.com/memory-use.html)",
   "gridPos": { "h": 7, "w": 5, "x": 14, "y": 1 },
   "yaxes": [
    { "format": "bits" }
   ],
   "targets": [
    { "expr": "rabbitmq_node_mem_used", "legendFormat": "{{node}}" }
   ]
  },
  {
   "title": "Disk",
   "type": "graph",
   "description": "* [Disk Space](https://www.rabbitmq.com/production-checklist.html#resource-limits-disk-space)\n* [Persistence Configuration](https://www.rabbitmq.com/persistence-conf.html)\n* [Free Disk Space Alarms](https://www.rabbitmq.com/disk-alarms.html)\n* [Lazy Queues](https://www.rabbitmq.com/lazy-queues.html)",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "rabbitmq_node_disk_free", "legendFormat": "{{node}}" }
   ]
  }
 ]
}