PROJECT = rabbitmq_stream_management
PROJECT_DESCRIPTION = RabbitMQ Stream Management
PROJECT_MOD = rabbit_stream_management

define PROJECT_ENV
[
]
endef


DEPS = rabbit rabbitmq_management rabbitmq_stream
TEST_DEPS = rabbitmq_ct_helpers rabbitmq_ct_client_helpers

DEP_EARLY_PLUGINS = rabbit_common/mk/rabbitmq-early-plugin.mk
DEP_PLUGINS = rabbit_common/mk/rabbitmq-plugin.mk

# FIXME: Use erlang.mk patched for RabbitMQ, while waiting for PRs to be
# reviewed and merged.

ERLANG_MK_REPO = https://github.com/rabbitmq/erlang.mk.git
ERLANG_MK_COMMIT = rabbitmq-tmp

include ../../rabbitmq-components.mk
include ../../erlang.mk
