FROM maven:3.9.9-eclipse-temurin-24-alpine as builder
WORKDIR /home/app/authorization-server
COPY ./ .
RUN mvn -Dmaven.test.skip=true clean package

FROM amazoncorretto:24-jdk
EXPOSE 8080
ENTRYPOINT ["java","-jar","/authorization-server.jar"]
ARG JAR_FILE=target/*.jar
COPY --from=builder /home/app/authorization-server/target/*.jar authorization-server.jar
