#!/bin/bash
# Escape spaces and quotes, because shell is revolting.
for arg in "$@" ; do
	# Escape quotes in parameters, so that they're passed through cleanly.
	arg=$(sed -e 's/"/\\"/' <<-END
		$arg
		END
	)
	CMDLINE="${CMDLINE} \"${arg}\""
done

cd /

if [ ${UID} = 0 ] ; then
    su rabbitmq -s /bin/sh -c "/usr/lib/rabbitmq/bin/rabbitmqctl ${CMDLINE}"

elif [ $# = 0 -o \( $# = 1 -a "$1" = --help \) ] ; then
    # Allow normal user to run for the help message
    /bin/sh -c "/usr/lib/rabbitmq/bin/rabbitmqctl ${CMDLINE}"

else
    echo "Only root should run $0"
    exit 1
fi

