#!/bin/sh
##   The contents of this file are subject to the Mozilla Public License
##   Version 1.1 (the "License"); you may not use this file except in
##   compliance with the License. You may obtain a copy of the License at
##   http://www.mozilla.org/MPL/
##
##   Software distributed under the License is distributed on an "AS IS"
##   basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See the
##   License for the specific language governing rights and limitations
##   under the License.
##
##   The Original Code is RabbitMQ.
##
##   The Initial Developers of the Original Code are LShift Ltd.,
##   Cohesive Financial Technologies LLC., and Rabbit Technologies Ltd.
##
##   Portions created by LShift Ltd., Cohesive Financial Technologies
##   LLC., and Rabbit Technologies Ltd. are Copyright (C) 2007-2008
##   LShift Ltd., Cohesive Financial Technologies LLC., and Rabbit
##   Technologies Ltd.;
##
##   All Rights Reserved.
##
##   Contributor(s): ______________________________________.
##

[ "x" = "x$NODENAME" ] && NODENAME=rabbit
[ "x" = "x$NODE_IP_ADDRESS" ] && NODE_IP_ADDRESS=0.0.0.0
[ "x" = "x$NODE_PORT" ] && NODE_PORT=5672

ERL_ARGS=
SCRIPT_HOME=$(dirname $0)

[ "x" = "x$PIDS_FILE" ] && PIDS_FILE=/var/lib/rabbitmq/pids

export NODENAME NODE_IP_ADDRESS NODE_PORT SCRIPT_HOME PIDS_FILE

exec erl \
    -pa ../ebin \
    -noinput \
    -hidden \
    ${ERL_ARGS} \
    -sname rabbitmq_multi$$ \
    -s rabbit_multi \
    ${START_ARGS} \
    -extra "$@"

