#!/bin/sh
##  The contents of this file are subject to the Mozilla Public License
##  Version 1.1 (the "License"); you may not use this file except in
##  compliance with the License. You may obtain a copy of the License
##  at http://www.mozilla.org/MPL/
##
##  Software distributed under the License is distributed on an "AS IS"
##  basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
##  the License for the specific language governing rights and
##  limitations under the License.
##
##  The Original Code is RabbitMQ.
##
##  The Initial Developer of the Original Code is VMware, Inc.
##  Copyright (c) 2012 VMware, Inc.  All rights reserved.
##

## Set system default values
SERVER_ERL_ARGS="+K true +A30 +P 1048576 \
-kernel inet_default_connect_options [{nodelay,true}]"

CONFIG_FILE=/etc/rabbitmq/rabbitmq

LOG_BASE=/var/log/rabbitmq

MNESIA_BASE=/var/lib/rabbitmq/mnesia

PLUGINS_DIR="${RABBITMQ_HOME}/plugins"

ENABLED_PLUGINS_FILE=/etc/rabbitmq/enabled_plugins
