#!/bin/sh
##  The contents of this file are subject to the Mozilla Public License
##  Version 1.1 (the "License"); you may not use this file except in
##  compliance with the License. You may obtain a copy of the License
##  at http://www.mozilla.org/MPL/
##
##  Software distributed under the License is distributed on an "AS IS"
##  basis, WITHOUT WARRANTY OF ANY KIND, either express or implied. See
##  the License for the specific language governing rights and
##  limitations under the License.
##
##  The Original Code is RabbitMQ.
##
##  The Initial Developer of the Original Code is GoPivotal, Inc.
##  Copyright (c) 2007-2014 GoPivotal, Inc.  All rights reserved.
##

# Get default settings with user overrides for (RABBITMQ_)<var_name>
# Non-empty defaults should be set in rabbitmq-env
. `dirname $0`/rabbitmq-env

##--- Set environment vars RABBITMQ_<var_name> to defaults if not set

[ "x" = "x$RABBITMQ_NODENAME" ] && RABBITMQ_NODENAME=${NODENAME}
[ "x" = "x$RABBITMQ_CTL_ERL_ARGS" ] && RABBITMQ_CTL_ERL_ARGS=${CTL_ERL_ARGS}

##--- End of overridden <var_name> variables

## SSL Dist Options
RABBITMQ_SSL_DIST_PA=""
if [ "x" != "x$RABBITMQ_SSL_DIST_ARGS" ]; then
    RABBITMQ_SSL_DIST_PA="-pa "`${ERL_DIR}erl -eval 'io:format("~p", [code:lib_dir(ssl, ebin)]),halt().' -noshell`
    RABBITMQ_SSL_DIST_ARGS="$RABBITMQ_SSL_DIST_ARGS -proto_dist inet_tls"
fi

exec ${ERL_DIR}erl \
    -pa "${RABBITMQ_HOME}/ebin" \
    ${RABBITMQ_SSL_DIST_PA} \
    "${RABBITMQ_SSL_DIST_ARGS}" \
    -noinput \
    -hidden \
    ${RABBITMQ_CTL_ERL_ARGS} \
    -sname rabbitmqctl$$ \
    -boot "${CLEAN_BOOT_FILE}" \
    -s rabbit_control_main \
    -nodename $RABBITMQ_NODENAME \
    -extra "$@"
