# This file is generated by rabbitmq-server via the elixir_config macro

load(
    "%{RABBITMQ_SERVER_WORKSPACE}//bazel/elixir:elixir_build.bzl",
    "elixir_external",
)
load(
    "%{RABBITMQ_SERVER_WORKSPACE}//bazel/elixir:elixir_toolchain.bzl",
    "elixir_toolchain",
)

elixir_external(
    name = "elixir_external",
    elixir_home = "%{ELIXIR_HOME}",
)

elixir_toolchain(
    name = "elixir",
    elixir = ":elixir_external",
    visibility = ["//visibility:public"],
)

toolchain(
    name = "toolchain",
    exec_compatible_with = [
        "//:elixir_external",
    ],
    target_compatible_with = [
        "//:elixir_%{ELIXIR_VERSION_ID}",
    ],
    toolchain = ":elixir",
    toolchain_type = "%{RABBITMQ_SERVER_WORKSPACE}//bazel/elixir:toolchain_type",
    visibility = ["//visibility:public"],
)
