=head1 NAME

rabbitmq-service - manage RabbitMQ AMQP service

=head1 SYNOPSIS

rabbitmq-service I<command>

=head1 DESCRIPTION

RabbitMQ is an implementation of AMQP, the emerging standard for high
performance enterprise messaging. The RabbitMQ server is a robust and
scalable implementation of an AMQP broker.

Running rabbitmq-service allows the RabbitMQ broker to be run as a
service on NT/2000/2003/XP/Vista® environments. The RabbitMQ broker 
service can be started and stopped using the Windows® services 
applet. 

By default the service will run in the authentication context of the 
local system account. It is therefore necessary to synchronise Erlang
cookies between the local system account (typically 
C<C:\WINDOWS\.erlang.cookie> and the account that will be used to
run rabbitctl.

=head1 COMMANDS

B<help> 
    Display usage information.

B<install> 
    Install the service. The service will not be started.
    Subsequent invocations will update the service parameters if
    relevant environment variables were modified.

B<remove> 
    Remove the service. If the service is running then it will
    automatically be stopped before being removed. No files will be
    deleted as a consequence and I<rabbitmq-server> will remain operable.

B<start> 
    Start the service. The service must have been correctly installed
    beforehand. 

B<stop> 
    Stop the service. The service must be running.

B<disable> 
    Disable the service. This is the equivalent of setting the startup
    type to I<Disabled> using the service control panel.

B<enable> 
    Enable the service. This is the equivalent of setting the startup
    type to I<Automatic> using the service control panel.

=head1 ENVIRONMENT

B<SERVICENAME>
    Defaults to RabbitMQ.
    This is the location of log and database directories.

B<RABBITMQ_BASE>
    Defaults to the application data directory of the current user.
    This is the location of log and database directories.

B<NODENAME>
    Defaults to rabbit. This can be useful if you want to run more
    than one node per machine - B<NODENAME> should be unique per
    erlang-node-and-machine combination. See clustering on a single
    machine guide
    at http://www.rabbitmq.com/clustering.html#single-machine for
    details. 

B<NODE_IP_ADDRESS>
    Defaults to 0.0.0.0. This can be changed if you only want to bind
    to one network interface. 

B<NODE_PORT>
    Defaults to 5672. 

B<ERLANG_SERVICE_MANAGER_PATH>
    Defaults to C<C:\Program Files\erl5.5.5\erts-5.5.5\bin>. This is 
    the installation location of the Erlang service manager.

B<CLUSTER_CONFIG_FILE>
    If this file is present it is used by the server to
    auto-configure a RabbitMQ cluster.  See the clustering guide
    at http://www.rabbitmq.com/clustering.html for details.


=head1 EXAMPLES

Start a previously-installed RabbitMQ AMQP service:

          rabbitmq-service start

=head1 SEE ALSO

rabbitmq-service(1), rabbitmqctl(1)

=head1 AUTHOR

Originally written by The RabbitMQ Team <info@lshift.net>

=head1 COPYRIGHT

This package, the RabbitMQ server is licensed under the MPL.

If you have any questions regarding licensing, please contact us at 
info@rabbitmq.com.

=head1 REFERENCES

RabbitMQ Web Site: http://www.rabbitmq.com
