=head1 NAME

rabbitmq-multi - start/stop local cluster RabbitMQ nodes

=head1 SYNOPSIS

rabbitmq-multi I<command> [command option]

=head1 DESCRIPTION

RabbitMQ is an implementation of AMQP, the emerging standard for high
performance enterprise messaging. The RabbitMQ server is a robust and
scalable implementation of an AMQP broker.

rabbitmq-multi scripts allows for easy set-up of a cluster on a single
machine.

See also L<rabbitmq-server(1)> for configuration information.

=head1 COMMANDS

=over

=item start_all I<count>

Start count nodes with unique names, listening on all IP addresses and
on sequential ports starting from 5672.

=item status

Print the status of all running RabbitMQ nodes.

=item stop_all

Stop all local RabbitMQ nodes,

=item rotate_logs

Rotate log files for all local and running RabbitMQ nodes.

=back

=head1 EXAMPLES

Start 3 local RabbitMQ nodes with unique, sequential port numbers:

          rabbitmq-multi start_all 3

=head1 SEE ALSO

L<rabbitmq.conf(5)>, L<rabbitmq-server(1)>, L<rabbitmqctl(1)>

=head1 AUTHOR

The RabbitMQ Team <info@rabbitmq.com>

=head1 REFERENCES

RabbitMQ Web Site: L<http://www.rabbitmq.com>
