=head1 NAME

rabbitmq-deactivate-plugins - command line tool for deactivating plugins
in a RabbitMQ broker

=head1 SYNOPSIS

rabbitmq-deactivate-plugins

=head1 DESCRIPTION

RabbitMQ is an implementation of AMQP, the emerging standard for high
performance enterprise messaging. The RabbitMQ server is a robust and
scalable implementation of an AMQP broker.

rabbitmq-deactivate-plugins is a command line tool for deactivating
plugins installed into the broker.

=head1 EXAMPLES

To deactivate all of the installed plugins in the current RabbitMQ install,
execute:

    rabbitmq-deactivate-plugins

=head1 SEE ALSO

L<rabbitmq.conf(5)>, L<rabbitmq-multi(1)>, L<rabbitmq-server(1)>,
L<rabbitmqctl(1)>, L<rabbitmq-activate-plugins(1)>

=head1 AUTHOR

The RabbitMQ Team <info@rabbitmq.com>

=head1 REFERENCES

RabbitMQ Web Site: L<http://www.rabbitmq.com>
