PROJECT = rabbitmq_prelaunch
PROJECT_DESCRIPTION = RabbitMQ prelaunch setup
PROJECT_VERSION = 1.0.0
PROJECT_MOD = rabbit_prelaunch_app

DEPS = rabbit_common cuttlefish jsx
dep_cuttlefish = hex 3.0.1

DEP_PLUGINS = rabbit_common/mk/rabbitmq-build.mk

include ../../../../rabbitmq-components.mk
include ../../../../erlang.mk
