#!/bin/bash
cd /var/lib/rabbitmq

SCRIPT=`basename $0`

if [ `id -u` = 0 ] ; then
    sudo -u rabbitmq -H /usr/lib/rabbitmq/bin/${SCRIPT} "$@"
elif [ `id -u` = `id -u rabbitmq` ] ; then
    /usr/lib/rabbitmq/bin/${SCRIPT} "$@"
else
    /usr/lib/rabbitmq/bin/${SCRIPT}
    echo -e "\nOnly root or rabbitmq should run ${SCRIPT}\n"
    exit 1
fi

