FROM node:24 AS base

WORKDIR /code

COPY package.json package.json

FROM base AS test
RUN --mount=type=secret,id=npmrc,target=/root/.npmrc,required=false npm install --verbose

ENTRYPOINT [ "npm" ]
CMD [ "" ]
