name: Update rules_erlang
on:
  schedule:
  - cron: '0 3 * * *'
  workflow_dispatch:
jobs:
  update-rules_erlang:
    name: Update rules_erlang
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: CHECKOUT REPOSITORY
      uses: actions/checkout@v2.4.0
      with:
        path: rabbitmq-server
    - name: CHECKOUT rules_erlang
      uses: actions/checkout@v2.4.0
      with:
        repository: rabbitmq/rules_erlang
        path: rules_erlang
    - name: DETERMINE LATEST COMMIT
      id: find-commit
      working-directory: rules_erlang
      run: |
        echo "::set-output name=SHA::$(git rev-parse HEAD)"
    - name: UPDATE rules_erlang COMMIT
      working-directory: rabbitmq-server
      run: |
        sudo npm install --global --silent @bazel/buildozer
        echo "$(cat WORKSPACE.bazel | npx buildozer 'set commit "${{ steps.find-commit.outputs.SHA }}"' -:rules_erlang)" > WORKSPACE.bazel
        git diff
    - name: CREATE PULL REQUEST
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.REPO_SCOPED_TOKEN }}
        committer: GitHub <noreply@github.com>
        author: GitHub <noreply@github.com>
        path: rabbitmq-server
        title: Adopt latest rules_erlang
        commit-message: |
          Adopt latest rules_erlang

          - rules_erlang@${{ steps.find-commit.outputs.SHA }}
        branch: bump-rules_erlang
        delete-branch: true